#ref: https://appfleet.com/blog/jenkins-pipeline-with-sonarqube-and-gitlab/

version: "3.2"
services:
   # Jenkins initial password located in: /var/jenkins_home/secrets/initialAdminPassword
   # to acccess: http://localhost:9000/jenkins
   jenkins:
   #   image: jenkinsci/jenkins:lts  # there is no image M1(arm64)
       image: jenkins/jenkins:latest
       container_name: jenkins-container
       restart: always
       networks:
           - sonarnet
       ports:
           - "9000:8080"
           - '50000:50000'
       volumes:
       - '/var/run/docker.sock:/var/run/docker.sock'
       - '/Users/koraygecici/Projects/DevOps/volumes/jenkins/jenkins_home:/var/jenkins_home'
       environment:
       - "JENKINS_OPTS=--prefix=/jenkins"
 
   # GitLab default user: root password is located in: /etc/gitlab/initial_root_password
   gitlab:
      #image: gitlab/gitlab-ce:latest  # there is no arm64 image for this, used below
       image: yrzr/gitlab-ce-arm64v8
       container_name: gitlab-container
       restart: always
       networks:
           - sonarnet
       environment:
           - GITLAB_SECRETS_DB_KEY_BASE=cdfv2309
           - GITLAB_HOST=127.0.0.1
           - GITLAB_PORT=9001
           - GITLAB_SSH_PORT=10022
       ports:
           - "9001:80"
           - "10022:22"
       expose:
           - "80"
       volumes:
       - '/Users/koraygecici/Projects/DevOps/volumes/gitlab/config:/etc/gitlab'
       - '/Users/koraygecici/Projects/DevOps/volumes/gitlab/logs:/var/log/gitlab'
       - '/Users/koraygecici/Projects/DevOps/volumes/gitlab/data:/var/opt/gitlab'
 
   sonarqube:
       image: sonarqube:9.9.0-community
       container_name: sonar-container
       restart: always
       networks:
           - sonarnet
       environment:
           - POSTGRESQL_HOST=postgressdb
           - POSTGRESQL_PORT=5432
           - POSTGRESQL_ROOT_USER=postgres
           - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=sonarqube
           - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=usr_sonarqube
           - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=cdfv2309
           - SONARQUBE_DATABASE_NAME=sonarqube
           - SONARQUBE_DATABASE_USER=usr_sonarqube
           - SONARQUBE_DATABASE_PASSWORD=cdfv2309
           #- SONARQUBE_JDBC_USERNAME=sonar
           #- SONARQUBE_JDBC_PASSWORD=cdfv2309
           #- SONARQUBE_JDBC_URL=jdbc:postgresql://postgressdb:5432/sonarqube
       ports:
       - "9002:9000"
       - "9092:9092"
       volumes:
       - '/Users/koraygecici/Projects/DevOps/volumes/sonar/sonarqube_conf:/opt/sonarqube/conf'
       - '/Users/koraygecici/Projects/DevOps/volumes/sonar/sonarqube_data:/opt/sonarqube/data'
       - '/Users/koraygecici/Projects/DevOps/volumes/sonar/sonarqube_extensions:/opt/sonarqube/extensions'
       - '/Users/koraygecici/Projects/DevOps/volumes/sonar/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins'
  
   postgressdb:
       image: postgres:12.1
       container_name: postgres-container
       restart: always
       networks:
           - sonarnet
       environment:
           - POSTGRES_USER=sonar
           - POSTGRES_PASSWORD=cdfv2309
           - POSTGRES_DB=sonarqube
       volumes:
           - '/Users/koraygecici/Projects/DevOps/volumes/postgresql/sonarqube_db:/var/lib/postgresql'
           - '/Users/koraygecici/Projects/DevOps/volumes/postgresql/postgresql_data:/var/lib/postgresql/data'
 
networks:
   sonarnet:
    driver: bridge